sudo: false
language: scala
jdk:
- oraclejdk8
before_install:
- export CXX='g++-4.8'
- nvm install 6.11.3 && nvm use 6.11.3 && npm install -g
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot"
  - "$HOME/.sbt/launchers"
  - node_modules
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - oracle-java8-installer
script:
- sbt textLintAll textTestAll textBuildHtml test &&
  wget -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/614d94496efdcf960871429e1c090c56d2018f68/setup/linux-installer.py
  | python -c "import sys; main=lambda x,y:sys.stderr.write('Download failed\n');
  exec(sys.stdin.read()); main('~/calibre-bin', True)" >/dev/null &&
  export PATH="~/calibre-bin/calibre/:/home/travis/calibre-bin/calibre/:$PATH" &&
  sbt "textBuildEpub"
after_success:
- "./deploy.sh"
after_script:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
- find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf
env:
  global:
  - secure: trVQXloshoD6qC8trtLviRLweSWOCJjq2TRHWuBcJqSJE8x7fJBcWnT2bex++gEPUQV2ee6cdF3/l/WcbPa+yaMDBvC3d4W/1WNXs8VxgI/M8UY5SfvB/nRnFGzxbGBW+AboHvvcvpDRk6jeTr+wQoRAKOIFOX6b3rcQfZh03RFIda9vOcCk48k1SpZKvcI9LHhB2ZA6pMeqk+KkaX8TKScVaOpoHJbnQT/uaMvPb0ZmdV2EKwOg6ZJffy3XPjwazWZWIg6mtPZwbHzVZGLSTnK8vlSqHwmBF49q9+3KjXe/DmBBMnTED+J8TNOv4eUSpmNlxQvBZVUgAVTQpIyQPdFmi6xzSWzS1AzW+ZUVMjTlyBUOzlAdOnqwtihtrvOLc3sGS8otMIBiuM49DWYCICYe/em0IFzsC6zK9okkoOC3Vw9U6Lgs/NvOlCwxpA0GFYpAGlfieqdfYnLVZDk8m0gSF37FcGxHQuRQlOk5f8c/JwvbU+FHBt5OFvGi3VeQ6mqOwPpYWz5Mz30tuKOXgH5RxDv5CLceSd0IsD5oHQEkFkP8m1woq6fUMCIlcv75w/1VVnMHTiTL9UqVnIvXCeEQFRpEZf/BWLe/C4QwrqowRGioZURemEnX4tzq0r9bYvPwIFw7akmDklSxzC2C/9vnpzRDtXJB33b/iGeTzeE=
  - secure: C1lYWCHCUCNzNGL0g2Hfu888bWe7930TIQVZ4aa6hDSHtRUOsHzSPGBCwd3+DMgFAWp64AJBxKcCiPJM7EbgfZnvCk2XKXo2MUErJIpEiLuXRuxkAiGr/DohYTNd+xL5uaXorqofR4XBGXF7DMvdQ4du8miuDwMtPy44ZVzZWcPisOySfjZfTyzK62GqlMPxVzPUcee9LW+C1OQkA0kYV8Vl7TxdzhVjpnrNKcqOsyBnQHe6EF1AxOsss/lOtoVNXMLQXzTU+j+Hs3shT17J524mmIBTsA+BXwJS1teLYjq/WdXVNnVuqlS/zCtW0f4Oge6yXkNUrFoh0fhkFaFE7PVZJQJUYZKwBNkHheA9/3uAYMPK26Qr8atvkBf7A02MNGIboBddNxbXGCQl9A56NHTBHWStFfXKs1TOzCyzaBV4FFsHrl1sjv1dFwgSN5mGGcWB+iUYB0Hmh27v6WUa1FFxKWn8wn5f/V1e/D1k2vCAFSaEViyMpOkmr/6ENVRpP2taJbx1cGUWYvadOlA2ilYbx7uRNmY/LB+5PgoN0rgOyEdh3MvHBSXqFaoHIVnryOUc1VK7w3ei6Xz9cFATv8O4M6gSj9i1bzDeUe/uOmIDJS0pQTEFNUOuEBo9rHBJydxPBoWgP5X/Sor8TMuXhH5KDlJMC1wD33E/L+v+b8Q=
  - secure: PTGMuzJsGtQOm2PUZGXqUaRWhxL7vlfAHQ8lNJpXg6BZBTomht19MwNmMhYFSs+jHdTzxC+ZROCgoaRPEHoD3a7ann1IBTJBuTbKxw2cZ8ApVMwCQo6y50og07VyJfEjvhijVVTGw5Qmk30oh1092VcvxpcxUloz0duSmwrBxhyyxivTHIqt6QuC/6Sw57dHhw+RVBG6SfnCYUVGjYK+iYDUsI1iWZCmGnzHKrjLuWbNsx5jp90vc/dp9BOd5qwZC3hUTblqbi8xXmGRUpJG8SUn/Y7a36jix15mIbifVhnVKmM7cnMX8+i4YWuRGQEevwKgZwDBYN6EzO2v5Nx14YeDpJ8d0E/nOdKraN/dgfLDqgGzDhNPOugGKKYoa2bCfhCxNSW1UcQUUSm6aLDi4SKewTjfbMJMslKSNwr2llpxK+UHVe16KPUKsRptQvK0WRZWYDXyGyGNt5dkiCI4/2tIudv0kqSG9Wv0ZiUAOpmecKqmgERZOU+LFF+uaMIGo8ff10ouDQlyr1LNl80DrI/zGEsDAAvYb3iIxk2i8HwSDj06X10iaFx+dlca/ma+GUpstH/YeFtL5cqZw18Rg92dWDBSNoD4a7CLWABgQviOSoeQK6Gesz50x+flpXjA2mOOGHL6lpzl67u5gXxUlkZKpSZPuFBlRLBkLCcmhOU=
notifications:
  slack:
    secure: bAx/wydlY/47lCu72ebmWFohDqY3Xq7dKyRK4pwd5Hqkxic/kPbM+znhNUdMS5IaaCfx8CkVYCG++DRzPaSmAXki8FbDac1SivsMTyMYqcV+YtLhVFKm2Mth4aCgDIDzWx2GQTvv4JVBvhEGpqbveitTMsV4ojzicQZy+VqUTQqdRGaGDD6M4SNpxJ0gV4qxGbunnXqqmbIz+eOfm4fwtbH7GFUyPMV1XiRnckxVzildDz14b9K99PzdG+NKa+0Tx3OW/SJ1TDYc+O8Z4X9Ut1CqW31k3NpdtIOSt4uFgiUwFhkxm34uEhi4nS5xRRdad4xqSfL3WtgXDaBynxt7qjSjFxue38byR1/3qBfR27vIfr/go1X75PFwwCq05LbQLCDBWiXXVKJ0P7xWHx/TYzdXRUvlF9/vmejmLk/NkDLOkrqANod19+cBVlzOWtLessX8XZZmB3bzIWHFs1l9mZl8rrIuA3LRv+6ZXZoX2VA6Iesh4UajRSV+z3mRYvTjDX6sEAjmzN2bb1VxJw2u1nz0jOapeXvROfycrPoflyYk/VKWI9kZbJK0bHX7ilXjRq+baOBRNlYBwVcbthXqpu1n0VBcQQCUgZ7/MjOyp3/0yQBWiJ5w7WKLtbaIHoy2ub7oqiONZkR7YxYw8fUqGDy5qZSGs5DpUJl3x+25LIo=
